# SIZES:
SCREENWIDTH = 1024
SCREENHEIGHT = 768
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)
CARDWIDTH = 80
CARDHEIGHT = 100
CARDSIZE = (CARDWIDTH, CARDHEIGHT)
OVERLAP = int(CARDWIDTH/4) # one can see at least 1/4 of each card
MARGIN = 5
CURSORWIDTH = 20
CURSORHEIGHT = 20
CURSORSIZE = (CURSORWIDTH, CURSORHEIGHT)

# COLORS:
GREEN = (0,100,0)
PINK = (200,50,200)

# OTHER:
TITLE = "Shithead"
FRAMERATE = 30
